---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  POSTGRES_DB: dGVzdGRhdGFiYXNl
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk
  POSTGRES_USER: dGVzdHVzZXI=