---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redmine-ingress
spec:
  rules:
    - http:
        paths:
          - path: /redmine
            pathType: Prefix
            backend:
              service:
                name: redmine
                port:
                  number: 3000