---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redmine
  name: redmine
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:4.2.5-alpine
          env:
            - name: REDMINE_DB_POSTGRES
              value: postgres
          envFrom:
            - secretRef:
                name: redmine-secret
          ports:
            - containerPort: 3000
              name: redmine